// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: queries.sql

package query

import (
	"context"
)

const markMigrationApplied = `-- name: MarkMigrationApplied :exec
insert into migrations (name) values (?1)
`

func (q *Queries) MarkMigrationApplied(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, markMigrationApplied, name)
	return err
}

const migrationApplied = `-- name: MigrationApplied :one
select exists (select 1 from migrations where name = ?1)
`

func (q *Queries) MigrationApplied(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, migrationApplied, name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
